### ISSUE TITLE
Unable to add images to the homepage pool

### ISSUE THREAD

**Issue by micahwalter** [collecting-social-photo/cosopho#3]
The dashboard allows you to add images to the homepage in a pool, but it's currently not working as expected.

**Comment by givp** [comment]
@micahwalter I've confirmed both API and UI are working as expected. But I'm unable to add photos to the Homepage pool in the Dashboard. Doesn't seem to update:

![Screen Recording 2020-10-07 at 11 56 54 AM](https://user-images.githubusercontent.com/205550/95375302-4a51f800-0894-11eb-9806-cf9f2180ce98.gif)

Over to you @revdancatt

**Comment by micahwalter** [comment]
Have traced this issue to the dashboard app. Using the API manually works fine. Also it seems I can't update additional metadata from the Dashboard.

**Comment by micahwalter** [comment]
OK I am pretty sure I've fixed this in the dashboard repo. I had to update the signature to match what the API was telling me and made a small edit to the file that makes calls to the API to send the user's apitoken instead of the HANDSHAKE. It works when I am logged in, but need to check for other users. Closing for now.
