### ISSUE TITLE
Can't edit text about an initiative

### ISSUE THREAD

**Issue by micahwalter** [collecting-social-photo/cosopho#4]
Each initiative has a small amount of descriptive text, but we currently can't make changes to this.

**Comment by givp** [comment]
@micahwalter I'm not able to reproduce this. I've tested updating the description text for an initiative and it was reflected in the app. Could you please clarify?

<img width="544" alt="Image 2020-10-07 at 12 01 53 PM" src="https://user-images.githubusercontent.com/205550/95375864-175c3400-0895-11eb-9d3c-65b7fd02b689.png">

<img width="341" alt="Image 2020-10-07 at 12 01 31 PM" src="https://user-images.githubusercontent.com/205550/95375887-204d0580-0895-11eb-8d47-df88684991ac.png">
